---
id: Token
name: Token
full: Tokens library
description: >-
  A library that provides a common abstracted interface into the various token
  generation mediums. It also includes all of the functions for retrieving,
  storing, and checking tokens.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Token
authors:
  -
    name: Gunnar Wrobel
    user: wrobel
    email: p@rdus.de
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha3
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/translation: ^3
      horde/url: ^3
      horde/util: ^3
    ext:
      hash: '*'
  optional:
    composer:
      horde/db: ^3
      horde/mongo: ^2
      horde/test: ^3
