language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
services:
  - mongodb
before_script:
  - export TOKEN_MONGO_TEST_CONFIG='{"token":{"mongo":"localhost"}}';
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ] || [ $(echo "$TRAVIS_PHP_VERSION 7.0" | tr " " "\n" | sort -V | head -n1) = "7.0" ];
    then
        phpenv config-add .travis.php7.ini;
    else
        phpenv config-add .travis.ini;
    fi
  - phpenv config-rm xdebug.ini || echo "XDebug not enabled"
  - pear install channel://pear.horde.org/Horde_Test
  - pear install -a -B package.xml
script:
  - php $(pear config-get php_dir)/Horde/Test/vendor/phpunit/phpunit/phpunit
