sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
services:
  - mongodb
before_script:
  - export TOKEN_MONGO_TEST_CONFIG='{"token":{"mongo":"localhost"}}';
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ] || [ $(echo "$TRAVIS_PHP_VERSION 7.0" | tr " " "\n" | sort -V | head -n1) = "7.0" ];
    then
        phpenv config-add .travis.php7.ini;
    else
        phpenv config-add .travis.ini;
    fi
  - phpenv config-rm xdebug.ini || echo "XDebug not enabled"
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ] || [ "$TRAVIS_PHP_VERSION" == "7.0" ];
    then
      echo "include_path = .:$HOME/.phpenv/versions/$(phpenv version-name)/lib/php/pear" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
      pear channel-discover pear.horde.org;
    fi

  - pear install channel://pear.horde.org/Horde_Test
  - pear install -a -B package.xml
script:
  - php $(find test -name AllTests.php)
